// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using static tunisair_back.Models.FDocLigne;

namespace tunisair_back.Models;

public partial class DTHDLGContext : DbContext
{
    public DTHDLGContext(DbContextOptions<DTHDLGContext> options)
        : base(options)
    {
    }

    public virtual DbSet<FArticle> FArticles { get; set; }
    public virtual DbSet<FArtGamme> FArtGammes { get; set; }

    public virtual DbSet<User> Users { get; set; }
    public DbSet<ProduitInventaire> ProduitsInventaire { get; set; }
    //public DbSet<FDocLigne> FDocLignes { get; set; }
    //public DbSet<FDocLigneAffectation> FDocLigneAffectations { get; set; }
    //public DbSet<FDocLigneAffectationUser> FDocLigneAffectationUsers { get; set; }

    public virtual DbSet<FDepot> FDepots { get; set; }
    public virtual DbSet<Inventaire> Inventaire { get; set; }
    public virtual DbSet<LigneInventaire> LigneInventaires { get; set; }
    public DbSet<UserInventaire> UserInventaires { get; set; }
    public virtual DbSet<FArtEnumRef> FArtEnumRefs { get; set; }

    public DbSet<UserDepot> UserDepots { get; set; }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("Users"); // Table nommée User
        });
        modelBuilder.Entity<FArtEnumRef>(entity =>
        {
            entity.ToTable("F_ARTENUMREF");

            entity.HasKey(e => e.AE_CodeBarre);

            entity.Property(e => e.AE_CodeBarre)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasColumnName("AE_CodeBarre");

            entity.Property(e => e.AR_Ref)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasColumnName("AR_Ref");
        });


        modelBuilder.Entity<FArtGamme>()
            .ToTable("F_ARTGAMME")
            .HasKey(x => x.AR_Ref);

        //modelBuilder.Entity<FDocLigneAffectation>(entity =>
        //{
        //    entity.ToTable("FDocLigneAffectation"); // Table nommée User
        //});
        //    modelBuilder.Entity<FDocLigneAffectationUser>()
        //.HasOne(x => x.LigneAffectation)
        //.WithMany(x => x.AffectationUsers)
        //.HasForeignKey(x => x.LigneAffectationId);

        //    modelBuilder.Entity<FDocLigneAffectationUser>()
        //        .HasOne(x => x.User)
        //        .WithMany()
        //        .HasForeignKey(x => x.UserId);
        //    modelBuilder.Entity<FDocLigne>(entity =>
        //    {
        //        entity.HasNoKey();
        //        entity.ToTable("F_DOCLIGNE");
        //    });


        modelBuilder.Entity<UserInventaire>()
       .HasKey(ui => new { ui.UserId, ui.InventaireId });

        modelBuilder.Entity<UserInventaire>()
            .HasOne(ui => ui.User)
            .WithMany(u => u.UserInventaires)
            .HasForeignKey(ui => ui.UserId);

        modelBuilder.Entity<UserInventaire>()
            .HasOne(ui => ui.Inventaire)
            .WithMany(i => i.UserInventaires)
            .HasForeignKey(ui => ui.InventaireId);

        modelBuilder.Entity<UserDepot>()
       .HasIndex(ud => new { ud.UserId, ud.DeNo })
       .IsUnique();

        modelBuilder.Entity<UserDepot>()
            .HasOne(ud => ud.User)
            .WithMany(u => u.UserDepots)
            .HasForeignKey(ud => ud.UserId);

        modelBuilder.Entity<UserDepot>()
            .HasOne(ud => ud.Depot)
            .WithMany(d => d.UserDepots)
            .HasForeignKey(ud => ud.DeNo);
        modelBuilder.Entity<LigneInventaire>(entity =>
        {
            entity.ToTable("LigneInventaire"); // Table nommée LigneInventaire
        });
        modelBuilder.Entity<ProduitInventaire>(entity =>
        {
            entity.ToTable("ProduitInventaire"); // Table nommée ProduitInventaire
        });
        modelBuilder.Entity<Inventaire>(entity =>
        {
            entity.ToTable("Inventaire"); // Table nommée Inventaire
        });
        modelBuilder.Entity<FArticle>(entity =>
        {
            entity.HasKey(e => e.CbMarq).HasName("PK_CBMARQ_F_ARTICLE");

            entity.ToTable("F_ARTICLE", tb =>
                {
                    tb.HasTrigger("TG_CBDEL_F_ARTICLE");
                    tb.HasTrigger("TG_CBINS_F_ARTICLE");
                    tb.HasTrigger("TG_CBUPD_F_ARTICLE");
                });

            entity.HasIndex(e => e.ArSubstitut, "FKIA_F_ARTICLE_AR_Ref");

            entity.HasIndex(e => e.CbClNo1, "FKIA_F_ARTICLE_CL_No1");

            entity.HasIndex(e => e.CbClNo2, "FKIA_F_ARTICLE_CL_No2");

            entity.HasIndex(e => e.CbClNo3, "FKIA_F_ARTICLE_CL_No3");

            entity.HasIndex(e => e.CbClNo4, "FKIA_F_ARTICLE_CL_No4");

            entity.HasIndex(e => e.RpCodeDefaut, "FKIA_F_ARTICLE_RP_Code");

            entity.HasIndex(e => e.CbArCodeBarre, "IAR_CBARRE");

            entity.HasIndex(e => new { e.CbArDesign, e.CbArRef }, "IAR_DESIGN");

            entity.HasIndex(e => new { e.ArNomencl, e.CbArDesign, e.CbArRef }, "IAR_DESIGNNOMENCL");

            entity.HasIndex(e => new { e.ArSommeil, e.CbArDesign, e.CbArRef }, "IAR_DESIGNSOM");

            entity.HasIndex(e => e.CbArEdiCode, "IAR_EDICODE");

            entity.HasIndex(e => new { e.ClNo1, e.CbArRef }, "IAR_EMPL1");

            entity.HasIndex(e => new { e.ClNo2, e.CbArRef }, "IAR_EMPL2");

            entity.HasIndex(e => new { e.ClNo3, e.CbArRef }, "IAR_EMPL3");

            entity.HasIndex(e => new { e.ClNo4, e.CbArRef }, "IAR_EMPL4");

            entity.HasIndex(e => new { e.CbFaCodeFamille, e.CbArRef }, "IAR_FAMILLE");

            entity.HasIndex(e => new { e.ArSommeil, e.CbFaCodeFamille, e.CbArRef }, "IAR_FAMILLESOM");

            entity.HasIndex(e => e.CbArRaccourci, "IAR_RACC");

            entity.HasIndex(e => e.CbArRef, "IAR_REF").IsUnique();

            entity.HasIndex(e => new { e.ArNomencl, e.CbArRef }, "IAR_REFNOMENCL");

            entity.HasIndex(e => new { e.ArSommeil, e.CbArRef }, "IAR_REFSOM");

            entity.HasIndex(e => new { e.ArSommeil, e.ClNo1, e.CbArRef }, "IAR_SOMEMPL1");

            entity.HasIndex(e => new { e.ArSommeil, e.ClNo2, e.CbArRef }, "IAR_SOMEMPL2");

            entity.HasIndex(e => new { e.ArSommeil, e.ClNo3, e.CbArRef }, "IAR_SOMEMPL3");

            entity.HasIndex(e => new { e.ArSommeil, e.ClNo4, e.CbArRef }, "IAR_SOMEMPL4");

            entity.HasIndex(e => e.CbArSubstitut, "IAR_SUBSTITUT");

            entity.HasIndex(e => new { e.ArType, e.CbArRef }, "IAR_TYPEREF");

            entity.HasIndex(e => e.ArRef, "UKA_F_ARTICLE_AR_Ref").IsUnique();

            entity.Property(e => e.CbMarq).HasColumnName("cbMarq");
            entity.Property(e => e.Ancref)
                .HasMaxLength(69)
                .IsUnicode(false)
                .HasColumnName("ANCREF");
            entity.Property(e => e.ArCodeBarre)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasColumnName("AR_CodeBarre");
            entity.Property(e => e.ArCodeFiscal)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("AR_CodeFiscal");
            entity.Property(e => e.ArCoef)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_Coef");
            entity.Property(e => e.ArCoefNouv)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_CoefNouv");
            entity.Property(e => e.ArCondition).HasColumnName("AR_Condition");
            entity.Property(e => e.ArContremarque).HasColumnName("AR_Contremarque");
            entity.Property(e => e.ArCoutStd)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_CoutStd");
            entity.Property(e => e.ArCriticite).HasColumnName("AR_Criticite");
            entity.Property(e => e.ArCycle).HasColumnName("AR_Cycle");
            entity.Property(e => e.ArDateApplication)
                .HasColumnType("datetime")
                .HasColumnName("AR_DateApplication");
            entity.Property(e => e.ArDateModif)
                .HasColumnType("datetime")
                .HasColumnName("AR_DateModif");
            entity.Property(e => e.ArDelai).HasColumnName("AR_Delai");
            entity.Property(e => e.ArDelaiFabrication).HasColumnName("AR_DelaiFabrication");
            entity.Property(e => e.ArDelaiPeremption).HasColumnName("AR_DelaiPeremption");
            entity.Property(e => e.ArDelaiSecurite).HasColumnName("AR_DelaiSecurite");
            entity.Property(e => e.ArDesign)
                .HasMaxLength(69)
                .IsUnicode(false)
                .HasColumnName("AR_Design");
            entity.Property(e => e.ArEdiCode)
                .HasMaxLength(45)
                .IsUnicode(false)
                .HasColumnName("AR_EdiCode");
            entity.Property(e => e.ArEscompte).HasColumnName("AR_Escompte");
            entity.Property(e => e.ArExclure).HasColumnName("AR_Exclure");
            entity.Property(e => e.ArFactForfait).HasColumnName("AR_FactForfait");
            entity.Property(e => e.ArFactPoids).HasColumnName("AR_FactPoids");
            entity.Property(e => e.ArFictif).HasColumnName("AR_Fictif");
            entity.Property(e => e.ArFrais01FrDenomination)
                .HasMaxLength(21)
                .IsUnicode(false)
                .HasColumnName("AR_Frais01FR_Denomination");
            entity.Property(e => e.ArFrais01FrRem01RemType).HasColumnName("AR_Frais01FR_Rem01REM_Type");
            entity.Property(e => e.ArFrais01FrRem01RemValeur)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_Frais01FR_Rem01REM_Valeur");
            entity.Property(e => e.ArFrais01FrRem02RemType).HasColumnName("AR_Frais01FR_Rem02REM_Type");
            entity.Property(e => e.ArFrais01FrRem02RemValeur)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_Frais01FR_Rem02REM_Valeur");
            entity.Property(e => e.ArFrais01FrRem03RemType).HasColumnName("AR_Frais01FR_Rem03REM_Type");
            entity.Property(e => e.ArFrais01FrRem03RemValeur)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_Frais01FR_Rem03REM_Valeur");
            entity.Property(e => e.ArFrais02FrDenomination)
                .HasMaxLength(21)
                .IsUnicode(false)
                .HasColumnName("AR_Frais02FR_Denomination");
            entity.Property(e => e.ArFrais02FrRem01RemType).HasColumnName("AR_Frais02FR_Rem01REM_Type");
            entity.Property(e => e.ArFrais02FrRem01RemValeur)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_Frais02FR_Rem01REM_Valeur");
            entity.Property(e => e.ArFrais02FrRem02RemType).HasColumnName("AR_Frais02FR_Rem02REM_Type");
            entity.Property(e => e.ArFrais02FrRem02RemValeur)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_Frais02FR_Rem02REM_Valeur");
            entity.Property(e => e.ArFrais02FrRem03RemType).HasColumnName("AR_Frais02FR_Rem03REM_Type");
            entity.Property(e => e.ArFrais02FrRem03RemValeur)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_Frais02FR_Rem03REM_Valeur");
            entity.Property(e => e.ArFrais03FrDenomination)
                .HasMaxLength(21)
                .IsUnicode(false)
                .HasColumnName("AR_Frais03FR_Denomination");
            entity.Property(e => e.ArFrais03FrRem01RemType).HasColumnName("AR_Frais03FR_Rem01REM_Type");
            entity.Property(e => e.ArFrais03FrRem01RemValeur)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_Frais03FR_Rem01REM_Valeur");
            entity.Property(e => e.ArFrais03FrRem02RemType).HasColumnName("AR_Frais03FR_Rem02REM_Type");
            entity.Property(e => e.ArFrais03FrRem02RemValeur)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_Frais03FR_Rem02REM_Valeur");
            entity.Property(e => e.ArFrais03FrRem03RemType).HasColumnName("AR_Frais03FR_Rem03REM_Type");
            entity.Property(e => e.ArFrais03FrRem03RemValeur)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_Frais03FR_Rem03REM_Valeur");
            entity.Property(e => e.ArGamme1).HasColumnName("AR_Gamme1");
            entity.Property(e => e.ArGamme2).HasColumnName("AR_Gamme2");
            entity.Property(e => e.ArGarantie).HasColumnName("AR_Garantie");
            entity.Property(e => e.ArHorsStat).HasColumnName("AR_HorsStat");
            entity.Property(e => e.ArInterdireCommande).HasColumnName("AR_InterdireCommande");
            entity.Property(e => e.ArLangue1)
                .HasMaxLength(69)
                .IsUnicode(false)
                .HasColumnName("AR_Langue1");
            entity.Property(e => e.ArLangue2)
                .HasMaxLength(69)
                .IsUnicode(false)
                .HasColumnName("AR_Langue2");
            entity.Property(e => e.ArNature).HasColumnName("AR_Nature");
            entity.Property(e => e.ArNbColis).HasColumnName("AR_NbColis");
            entity.Property(e => e.ArNomencl).HasColumnName("AR_Nomencl");
            entity.Property(e => e.ArNotImp).HasColumnName("AR_NotImp");
            entity.Property(e => e.ArPays)
                .HasMaxLength(35)
                .IsUnicode(false)
                .HasColumnName("AR_Pays");
            entity.Property(e => e.ArPhoto)
                .HasMaxLength(259)
                .IsUnicode(false)
                .HasColumnName("AR_Photo");
            entity.Property(e => e.ArPoidsBrut)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_PoidsBrut");
            entity.Property(e => e.ArPoidsNet)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_PoidsNet");
            entity.Property(e => e.ArPrevision).HasColumnName("AR_Prevision");
            entity.Property(e => e.ArPrixAch)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_PrixAch");
            entity.Property(e => e.ArPrixAchNouv)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_PrixAchNouv");
            entity.Property(e => e.ArPrixTtc).HasColumnName("AR_PrixTTC");
            entity.Property(e => e.ArPrixVen)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_PrixVen");
            entity.Property(e => e.ArPrixVenNouv)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_PrixVenNouv");
            entity.Property(e => e.ArPublie).HasColumnName("AR_Publie");
            entity.Property(e => e.ArPunet)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_PUNet");
            entity.Property(e => e.ArQteComp)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_QteComp");
            entity.Property(e => e.ArQteOperatoire)
                .HasColumnType("numeric(24, 6)")
                .HasColumnName("AR_QteOperatoire");
            entity.Property(e => e.ArRaccourci)
                .HasMaxLength(7)
                .IsUnicode(false)
                .HasColumnName("AR_Raccourci");
            entity.Property(e => e.ArRef)
                .IsRequired()
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasColumnName("AR_Ref");
            entity.Property(e => e.ArSaisieVar).HasColumnName("AR_SaisieVar");
            entity.Property(e => e.ArSommeil).HasColumnName("AR_Sommeil");
            entity.Property(e => e.ArSousTraitance).HasColumnName("AR_SousTraitance");
            entity.Property(e => e.ArStat01)
                .HasMaxLength(21)
                .IsUnicode(false)
                .HasColumnName("AR_Stat01");
            entity.Property(e => e.ArStat02)
                .HasMaxLength(21)
                .IsUnicode(false)
                .HasColumnName("AR_Stat02");
            entity.Property(e => e.ArStat03)
                .HasMaxLength(21)
                .IsUnicode(false)
                .HasColumnName("AR_Stat03");
            entity.Property(e => e.ArStat04)
                .HasMaxLength(21)
                .IsUnicode(false)
                .HasColumnName("AR_Stat04");
            entity.Property(e => e.ArStat05)
                .HasMaxLength(21)
                .IsUnicode(false)
                .HasColumnName("AR_Stat05");
            entity.Property(e => e.ArSubstitut)
                .HasMaxLength(19)
                .IsUnicode(false)
                .HasColumnName("AR_Substitut");
            entity.Property(e => e.ArSuiviStock).HasColumnName("AR_SuiviStock");
            entity.Property(e => e.ArTransfere).HasColumnName("AR_Transfere");
            entity.Property(e => e.ArType).HasColumnName("AR_Type");
            entity.Property(e => e.ArTypeLancement).HasColumnName("AR_TypeLancement");
            entity.Property(e => e.ArUnitePoids).HasColumnName("AR_UnitePoids");
            entity.Property(e => e.ArUniteVen).HasColumnName("AR_UniteVen");
            entity.Property(e => e.ArVteDebit).HasColumnName("AR_VteDebit");
            entity.Property(e => e.CbArCodeBarre)
                .HasMaxLength(20)
                .HasComputedColumnSql("(CONVERT([varbinary](20),isnull([AR_CodeBarre],'')))", false)
                .HasColumnName("cbAR_CodeBarre");
            entity.Property(e => e.CbArDesign)
                .HasMaxLength(70)
                .HasComputedColumnSql("(CONVERT([varbinary](70),isnull([AR_Design],'')))", false)
                .HasColumnName("cbAR_Design");
            entity.Property(e => e.CbArEdiCode)
                .HasMaxLength(46)
                .HasComputedColumnSql("(CONVERT([varbinary](46),isnull([AR_EdiCode],'')))", false)
                .HasColumnName("cbAR_EdiCode");
            entity.Property(e => e.CbArRaccourci)
                .HasMaxLength(8)
                .HasComputedColumnSql("(CONVERT([varbinary](8),isnull([AR_Raccourci],'')))", false)
                .HasColumnName("cbAR_Raccourci");
            entity.Property(e => e.CbArRef)
                .HasMaxLength(20)
                .HasComputedColumnSql("(CONVERT([varbinary](20),[AR_Ref]))", false)
                .HasColumnName("cbAR_Ref");
            entity.Property(e => e.CbArSubstitut)
                .HasMaxLength(20)
                .HasComputedColumnSql("(CONVERT([varbinary](20),isnull([AR_Substitut],'')))", false)
                .HasColumnName("cbAR_Substitut");
            entity.Property(e => e.CbClNo1).HasColumnName("cbCL_No1");
            entity.Property(e => e.CbClNo2).HasColumnName("cbCL_No2");
            entity.Property(e => e.CbClNo3).HasColumnName("cbCL_No3");
            entity.Property(e => e.CbClNo4).HasColumnName("cbCL_No4");
            entity.Property(e => e.CbCoNo).HasColumnName("cbCO_No");
            entity.Property(e => e.CbCreateur)
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasDefaultValue("CSQL")
                .IsFixedLength()
                .HasColumnName("cbCreateur");
            entity.Property(e => e.CbCreation)
                .HasDefaultValueSql("(CONVERT([datetime2](0),getdate()))")
                .HasColumnType("datetime")
                .HasColumnName("cbCreation");
            entity.Property(e => e.CbCreationUser).HasColumnName("cbCreationUser");
            entity.Property(e => e.CbFaCodeFamille)
                .HasMaxLength(12)
                .HasComputedColumnSql("(CONVERT([varbinary](12),[FA_CodeFamille]))", false)
                .HasColumnName("cbFA_CodeFamille");
            entity.Property(e => e.CbFlag)
                .HasDefaultValue((short)0)
                .HasColumnName("cbFlag");
            entity.Property(e => e.CbModification)
                .HasDefaultValueSql("(CONVERT([datetime2](0),getdate()))")
                .HasColumnType("datetime")
                .HasColumnName("cbModification");
            entity.Property(e => e.CbProt)
                .HasDefaultValue((short)0)
                .HasColumnName("cbProt");
            entity.Property(e => e.CbReplication)
                .HasDefaultValue(0)
                .HasColumnName("cbReplication");
            entity.Property(e => e.ClNo1).HasColumnName("CL_No1");
            entity.Property(e => e.ClNo2).HasColumnName("CL_No2");
            entity.Property(e => e.ClNo3).HasColumnName("CL_No3");
            entity.Property(e => e.ClNo4).HasColumnName("CL_No4");
            entity.Property(e => e.CoNo).HasColumnName("CO_No");
            entity.Property(e => e.FaCodeFamille)
                .IsRequired()
                .HasMaxLength(11)
                .IsUnicode(false)
                .HasColumnName("FA_CodeFamille");
            entity.Property(e => e.RpCodeDefaut)
                .HasMaxLength(11)
                .IsUnicode(false)
                .HasColumnName("RP_CodeDefaut");

            entity.HasOne(d => d.ArSubstitutNavigation).WithMany(p => p.InverseArSubstitutNavigation)
                .HasPrincipalKey(p => p.ArRef)
                .HasForeignKey(d => d.ArSubstitut)
                .HasConstraintName("FKA_F_ARTICLE_AR_Ref");
        });

        modelBuilder.Entity<FDepot>(entity =>
        {
            entity.HasKey(e => e.CbMarq).HasName("PK_CBMARQ_F_DEPOT");

            entity.ToTable("F_DEPOT", tb =>
                {
                    tb.HasTrigger("TG_CBDEL_F_DEPOT");
                    tb.HasTrigger("TG_CBINS_F_DEPOT");
                    tb.HasTrigger("TG_CBUPD_F_DEPOT");
                });

            entity.HasIndex(e => e.CbDpNoDefaut, "FKIA_F_DEPOT_DP_NoDefaut");

            entity.HasIndex(e => e.CbDeCode, "IDE_CODE");

            entity.HasIndex(e => new { e.DeExclure, e.CbDeIntitule }, "IDE_EXCLURE");

            entity.HasIndex(e => e.CbDeIntitule, "IDE_INTITULE").IsUnique();

            entity.HasIndex(e => e.DeNo, "IDE_NO").IsUnique();

            entity.HasIndex(e => e.DePrincipal, "IDE_PRINCIPAL");

            entity.Property(e => e.CbMarq).HasColumnName("cbMarq");
            entity.Property(e => e.CbCreateur)
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasDefaultValue("CSQL")
                .IsFixedLength()
                .HasColumnName("cbCreateur");
            entity.Property(e => e.CbCreation)
                .HasDefaultValueSql("(CONVERT([datetime2](0),getdate()))")
                .HasColumnType("datetime")
                .HasColumnName("cbCreation");
            entity.Property(e => e.CbCreationUser).HasColumnName("cbCreationUser");
            entity.Property(e => e.CbDeCode)
                .HasMaxLength(10)
                .HasComputedColumnSql("(CONVERT([varbinary](10),isnull([DE_Code],'')))", false)
                .HasColumnName("cbDE_Code");
            entity.Property(e => e.CbDeIntitule)
                .HasMaxLength(36)
                .HasComputedColumnSql("(CONVERT([varbinary](36),[DE_Intitule]))", false)
                .HasColumnName("cbDE_Intitule");
            entity.Property(e => e.CbDpNoDefaut).HasColumnName("cbDP_NoDefaut");
            entity.Property(e => e.CbFlag)
                .HasDefaultValue((short)0)
                .HasColumnName("cbFlag");
            entity.Property(e => e.CbModification)
                .HasDefaultValueSql("(CONVERT([datetime2](0),getdate()))")
                .HasColumnType("datetime")
                .HasColumnName("cbModification");
            entity.Property(e => e.CbProt)
                .HasDefaultValue((short)0)
                .HasColumnName("cbProt");
            entity.Property(e => e.CbReplication)
                .HasDefaultValue(0)
                .HasColumnName("cbReplication");
            entity.Property(e => e.DeAdresse)
                .HasMaxLength(35)
                .IsUnicode(false)
                .HasColumnName("DE_Adresse");
            entity.Property(e => e.DeCatCompta).HasColumnName("DE_CatCompta");
            entity.Property(e => e.DeCode)
                .HasMaxLength(9)
                .IsUnicode(false)
                .HasColumnName("DE_Code");
            entity.Property(e => e.DeCodePostal)
                .HasMaxLength(9)
                .IsUnicode(false)
                .HasColumnName("DE_CodePostal");
            entity.Property(e => e.DeComplement)
                .HasMaxLength(35)
                .IsUnicode(false)
                .HasColumnName("DE_Complement");
            entity.Property(e => e.DeContact)
                .HasMaxLength(35)
                .IsUnicode(false)
                .HasColumnName("DE_Contact");
            entity.Property(e => e.DeEmail)
                .HasMaxLength(69)
                .IsUnicode(false)
                .HasColumnName("DE_EMail");
            entity.Property(e => e.DeExclure).HasColumnName("DE_Exclure");
            entity.Property(e => e.DeIntitule)
                .IsRequired()
                .HasMaxLength(35)
                .IsUnicode(false)
                .HasColumnName("DE_Intitule");
            entity.Property(e => e.DeNo).HasColumnName("DE_No");
            entity.Property(e => e.DePays)
                .HasMaxLength(35)
                .IsUnicode(false)
                .HasColumnName("DE_Pays");
            entity.Property(e => e.DePrincipal).HasColumnName("DE_Principal");
            entity.Property(e => e.DeRegion)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("DE_Region");
            entity.Property(e => e.DeReplication).HasColumnName("DE_Replication");
            entity.Property(e => e.DeSouche01).HasColumnName("DE_Souche01");
            entity.Property(e => e.DeSouche02).HasColumnName("DE_Souche02");
            entity.Property(e => e.DeSouche03).HasColumnName("DE_Souche03");
            entity.Property(e => e.DeTelecopie)
                .HasMaxLength(21)
                .IsUnicode(false)
                .HasColumnName("DE_Telecopie");
            entity.Property(e => e.DeTelephone)
                .HasMaxLength(21)
                .IsUnicode(false)
                .HasColumnName("DE_Telephone");
            entity.Property(e => e.DeVille)
                .HasMaxLength(35)
                .IsUnicode(false)
                .HasColumnName("DE_Ville");
            entity.Property(e => e.DpNoDefaut).HasColumnName("DP_NoDefaut");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}