// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace tunisair_back.Models;

public partial class FArtGamme
{
    public string AR_Ref { get; set; }

    public byte[] CbAR_Ref { get; set; }

    public int? AG_No { get; set; }

    public string EG_Enumere { get; set; }

    public byte[] CbEG_Enumere { get; set; }

    public short? AG_Type { get; set; }

    public short? CbProt { get; set; }

    public int CbMarq { get; set; }

    public string CbCreateur { get; set; }

    public DateTime? CbModification { get; set; }

    public int? CbReplication { get; set; }

    public short? CbFlag { get; set; }

    public DateTime? CbCreation { get; set; }

    public Guid? CbCreationUser { get; set; }
}
