// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tunisair_back.Models;

public partial class FArticle
{
    public string ArRef { get; set; }

    public byte[] CbArRef { get; set; }

    public string ArDesign { get; set; }

    public byte[] CbArDesign { get; set; }

    public string FaCodeFamille { get; set; }

    public byte[] CbFaCodeFamille { get; set; }

    public string ArSubstitut { get; set; }

    public byte[] CbArSubstitut { get; set; }

    public string ArRaccourci { get; set; }

    public byte[] CbArRaccourci { get; set; }

    public short? ArGarantie { get; set; }

    public short? ArUnitePoids { get; set; }

    public decimal? ArPoidsNet { get; set; }

    public decimal? ArPoidsBrut { get; set; }

    public short? ArUniteVen { get; set; }

    public decimal? ArPrixAch { get; set; }

    public decimal? ArCoef { get; set; }

    public decimal? ArPrixVen { get; set; }

    public short? ArPrixTtc { get; set; }

    public short? ArGamme1 { get; set; }

    public short? ArGamme2 { get; set; }

    public short? ArSuiviStock { get; set; }

    public short? ArNomencl { get; set; }

    public string ArStat01 { get; set; }

    public string ArStat02 { get; set; }

    public string ArStat03 { get; set; }

    public string ArStat04 { get; set; }

    public string ArStat05 { get; set; }

    public short? ArEscompte { get; set; }

    public short? ArDelai { get; set; }

    public short? ArHorsStat { get; set; }

    public short? ArVteDebit { get; set; }

    public short? ArNotImp { get; set; }

    public short? ArSommeil { get; set; }

    public string ArLangue1 { get; set; }

    public string ArLangue2 { get; set; }

    public string ArEdiCode { get; set; }

    public byte[] CbArEdiCode { get; set; }

    public string ArCodeBarre { get; set; }

    public byte[] CbArCodeBarre { get; set; }

    public string ArCodeFiscal { get; set; }

    public string ArPays { get; set; }

    public string ArFrais01FrDenomination { get; set; }

    public decimal? ArFrais01FrRem01RemValeur { get; set; }

    public short? ArFrais01FrRem01RemType { get; set; }

    public decimal? ArFrais01FrRem02RemValeur { get; set; }

    public short? ArFrais01FrRem02RemType { get; set; }

    public decimal? ArFrais01FrRem03RemValeur { get; set; }

    public short? ArFrais01FrRem03RemType { get; set; }

    public string ArFrais02FrDenomination { get; set; }

    public decimal? ArFrais02FrRem01RemValeur { get; set; }

    public short? ArFrais02FrRem01RemType { get; set; }

    public decimal? ArFrais02FrRem02RemValeur { get; set; }

    public short? ArFrais02FrRem02RemType { get; set; }

    public decimal? ArFrais02FrRem03RemValeur { get; set; }

    public short? ArFrais02FrRem03RemType { get; set; }

    public string ArFrais03FrDenomination { get; set; }

    public decimal? ArFrais03FrRem01RemValeur { get; set; }

    public short? ArFrais03FrRem01RemType { get; set; }

    public decimal? ArFrais03FrRem02RemValeur { get; set; }

    public short? ArFrais03FrRem02RemType { get; set; }

    public decimal? ArFrais03FrRem03RemValeur { get; set; }

    public short? ArFrais03FrRem03RemType { get; set; }

    public short? ArCondition { get; set; }

    public decimal? ArPunet { get; set; }

    public short? ArContremarque { get; set; }

    public short? ArFactPoids { get; set; }

    public short? ArFactForfait { get; set; }

    public short? ArSaisieVar { get; set; }

    public short? ArTransfere { get; set; }

    public short? ArPublie { get; set; }

    public DateTime? ArDateModif { get; set; }

    public string ArPhoto { get; set; }

    public decimal? ArPrixAchNouv { get; set; }

    public decimal? ArCoefNouv { get; set; }

    public decimal? ArPrixVenNouv { get; set; }

    public DateTime? ArDateApplication { get; set; }

    public decimal? ArCoutStd { get; set; }

    public decimal? ArQteComp { get; set; }

    public decimal? ArQteOperatoire { get; set; }

    public int? CoNo { get; set; }

    public int? CbCoNo { get; set; }

    public short? ArPrevision { get; set; }

    public int? ClNo1 { get; set; }

    public int? CbClNo1 { get; set; }

    public int? ClNo2 { get; set; }

    public int? CbClNo2 { get; set; }

    public int? ClNo3 { get; set; }

    public int? CbClNo3 { get; set; }

    public int? ClNo4 { get; set; }

    public int? CbClNo4 { get; set; }

    public short? ArType { get; set; }

    public string RpCodeDefaut { get; set; }

    public short? ArNature { get; set; }

    public short? ArDelaiFabrication { get; set; }

    public short? ArNbColis { get; set; }

    public short? ArDelaiPeremption { get; set; }

    public short? ArDelaiSecurite { get; set; }

    public short? ArFictif { get; set; }

    public short? ArSousTraitance { get; set; }

    public short? ArTypeLancement { get; set; }

    public short? ArCycle { get; set; }

    public short? ArCriticite { get; set; }

    public short? CbProt { get; set; }

    public int CbMarq { get; set; }

    public string CbCreateur { get; set; }

    public DateTime? CbModification { get; set; }

    public int? CbReplication { get; set; }

    public short? CbFlag { get; set; }

    public string Ancref { get; set; }

    public DateTime? CbCreation { get; set; }

    public Guid? CbCreationUser { get; set; }

    public short? ArInterdireCommande { get; set; }

    public short? ArExclure { get; set; }

    public virtual FArticle ArSubstitutNavigation { get; set; }

    public virtual ICollection<FArticle> InverseArSubstitutNavigation { get; set; } = new List<FArticle>();
}