// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tunisair_back.Models;

public partial class FDepot
{
    public int? DeNo { get; set; }

    public string DeIntitule { get; set; }

    public byte[] CbDeIntitule { get; set; }

    public string DeAdresse { get; set; }

    public string DeComplement { get; set; }

    public string DeCodePostal { get; set; }

    public string DeVille { get; set; }

    public string DeContact { get; set; }

    public short? DePrincipal { get; set; }

    public short? DeCatCompta { get; set; }

    public string DeRegion { get; set; }

    public string DePays { get; set; }

    public string DeEmail { get; set; }

    public string DeCode { get; set; }

    public byte[] CbDeCode { get; set; }

    public string DeTelephone { get; set; }

    public string DeTelecopie { get; set; }

    public int? DeReplication { get; set; }

    public int? DpNoDefaut { get; set; }

    public int? CbDpNoDefaut { get; set; }

    public short? DeExclure { get; set; }

    public short? DeSouche01 { get; set; }

    public short? DeSouche02 { get; set; }

    public short? DeSouche03 { get; set; }

    public short? CbProt { get; set; }

    public int CbMarq { get; set; }

    public string CbCreateur { get; set; }

    public DateTime? CbModification { get; set; }

    public int? CbReplication { get; set; }

    public short? CbFlag { get; set; }

    public DateTime? CbCreation { get; set; }

    public Guid? CbCreationUser { get; set; }
    public ICollection<UserDepot> UserDepots { get; set; }

}